-- MySQL Script generated by MySQL Workbench
-- Sat May 25 20:23:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema restaurant
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurant
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurant` ;
USE `restaurant` ;

-- -----------------------------------------------------
-- Table `restaurant`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`client` (
  `client_id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `surname` VARCHAR(45) NULL,
  `name` VARCHAR(30) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`client_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`receiving_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`receiving_type` (
  `receiving_type_id` INT NOT NULL,
  `type` ENUM('Самовивіз', 'Доставлення') NOT NULL,
  PRIMARY KEY (`receiving_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`status` (
  `status_id` INT NOT NULL,
  `type` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(45) NULL,
  `name` VARCHAR(30) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `address` VARCHAR(100) NULL,
  `order_price` DECIMAL(10,2) NOT NULL,
  `order_datetime` DATETIME NULL,
  `fk_client_id` INT NULL,
  `fk_receiving_type_id` INT NOT NULL,
  `fk_status_id` INT NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_oder_client_idx` (`fk_client_id` ASC) VISIBLE,
  INDEX `fk_order_receiving_type1_idx` (`fk_receiving_type_id` ASC) VISIBLE,
  INDEX `fk_order_status1_idx` (`fk_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_oder_client`
    FOREIGN KEY (`fk_client_id`)
    REFERENCES `restaurant`.`client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_receiving_type1`
    FOREIGN KEY (`fk_receiving_type_id`)
    REFERENCES `restaurant`.`receiving_type` (`receiving_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_status1`
    FOREIGN KEY (`fk_status_id`)
    REFERENCES `restaurant`.`status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`employee_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`employee_type` (
  `employee_type_id` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM('Менеджер', 'Офіціант') NOT NULL,
  PRIMARY KEY (`employee_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`employee` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `fk_employee_type_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`),
  INDEX `fk_employee_employee_type1_idx` (`fk_employee_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_employee_type1`
    FOREIGN KEY (`fk_employee_type_id`)
    REFERENCES `restaurant`.`employee_type` (`employee_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`category` (
  `category_id` INT NOT NULL,
  `name` ENUM('Страва', 'Напій') NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `description` VARCHAR(255) NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `image_path` VARCHAR(255) NULL,
  `fk_category_id` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_product_category1_idx` (`fk_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`fk_category_id`)
    REFERENCES `restaurant`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`banquet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`banquet` (
  `banquet_id` INT NOT NULL AUTO_INCREMENT,
  `banquet_datetime` DATETIME NOT NULL,
  `number_guests` INT NOT NULL,
  `additional_wishes` VARCHAR(255) NULL,
  `sending_datetime` DATETIME NULL,
  `fk_client_id` INT NOT NULL,
  `fk_status_id` INT NOT NULL,
  PRIMARY KEY (`banquet_id`),
  INDEX `fk_banquet_client1_idx` (`fk_client_id` ASC) VISIBLE,
  INDEX `fk_banquet_status1_idx` (`fk_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_banquet_client1`
    FOREIGN KEY (`fk_client_id`)
    REFERENCES `restaurant`.`client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_banquet_status1`
    FOREIGN KEY (`fk_status_id`)
    REFERENCES `restaurant`.`status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`order_item` (
  `order_item_id` INT NOT NULL AUTO_INCREMENT,
  `fk_order_id` INT NOT NULL,
  `fk_product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`order_item_id`, `fk_order_id`, `fk_product_id`),
  INDEX `fk_order_has_product_product1_idx` (`fk_product_id` ASC) VISIBLE,
  INDEX `fk_order_has_product_order1_idx` (`fk_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_has_product_order1`
    FOREIGN KEY (`fk_order_id`)
    REFERENCES `restaurant`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_product_product1`
    FOREIGN KEY (`fk_product_id`)
    REFERENCES `restaurant`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
